/* Questions over SokkerLiga's own history — the arithmetic half.
 *
 * "How accurate have our Premier League Over 2.5 predictions been?"
 * Claude turns the question into a filter (ai/questions.mjs); this file
 * checks the filter against what exists, runs it, and writes the answer
 * from the numbers. Nothing here is generated by Claude.
 */

import { ValidationError } from './db.mjs';
import { grouped } from './performance.mjs';
import { thresholdsFor } from './analysis.mjs';
import { bettingHistory } from './bets.mjs';
import { formatMoney } from '../src/odds.js';

const pct = (x, d = 1) => (x === null || x === undefined ? '—' : `${(x * 100).toFixed(d)}%`);

/** What Claude may refer to: keys and names it maps the question onto. */
export function questionContext(db, now = new Date()) {
  return {
    today: now.toISOString().slice(0, 10),
    competitions: db.prepare('SELECT key, name, country_name AS country FROM competitions ORDER BY ordinal').all(),
    markets: db.prepare('SELECT key, name, has_line AS hasLine FROM market_types ORDER BY ordinal').all(),
    selections: {
      match_result: ['home', 'draw', 'away'], double_chance: ['home_draw', 'home_away', 'draw_away'],
      draw_no_bet: ['home', 'away'], over_under: ['over', 'under'], btts: ['yes', 'no'],
      asian_handicap: ['home', 'away'], european_handicap: ['home', 'draw', 'away'], home_total: ['over', 'under'],
      away_total: ['over', 'under'], corners_ou: ['over', 'under'], cards_ou: ['over', 'under'],
    },
  };
}

const DIMENSION = { market: 'market', competition: 'competition_id', confidence: 'confidence_band',
  month: 'substr(kickoff_utc, 1, 7)', source: 'source' };

/** Validate Claude's filter against the database; unknown keys are dropped and reported. */
export function resolveFilter(db, raw) {
  const notes = [];
  const comps = db.prepare('SELECT id, key, name FROM competitions').all();
  const markets = new Set(db.prepare('SELECT key FROM market_types').all().map((r) => r.key));
  const competitions = (raw.competitions ?? []).map((k) => {
    const c = comps.find((x) => x.key === k);
    if (!c) notes.push(`Unknown competition "${k}" ignored.`);
    return c;
  }).filter(Boolean);
  const marketKeys = (raw.markets ?? []).filter((k) => {
    if (!markets.has(k)) notes.push(`Unknown market "${k}" ignored.`);
    return markets.has(k);
  });
  let team = null;
  if (raw.team) {
    team = db.prepare(`SELECT t.id, t.name, (SELECT COUNT(*) FROM matches m WHERE m.home_team_id = t.id OR m.away_team_id = t.id) AS n
                       FROM teams t WHERE t.name LIKE ? ORDER BY n DESC LIMIT 1`).get(`%${raw.team}%`) ?? null;
    if (!team) notes.push(`No team called "${raw.team}"; the question was answered for all teams.`);
  }
  const date = (d) => (d && /^\d{4}-\d{2}-\d{2}$/.test(d) ? d : null);
  return {
    subject: ['predictions', 'recommendations', 'bets'].includes(raw.subject) ? raw.subject : 'predictions',
    source: ['live', 'backtest'].includes(raw.source) ? raw.source : null,
    competitions, markets: marketKeys,
    line: Number.isFinite(raw.line) ? raw.line : null,
    selection: raw.selection || null,
    confidences: (raw.confidence ?? []).filter((c) => ['low', 'medium', 'high'].includes(c)),
    team, favourite: raw.favourite === 'home' || raw.favourite === 'away' ? raw.favourite : null,
    from: date(raw.from), to: date(raw.to),
    groupBy: raw.group_by && raw.group_by !== 'none' ? raw.group_by : null,
    restatement: raw.restatement ?? '', notes,
  };
}

/** Run a resolved filter. */
export function runFilter(db, userId, f) {
  if (f.subject === 'bets') return betsAnswer(db, userId, f);
  const filters = {
    source: f.source, competitions: f.competitions.map((c) => c.id), markets: f.markets, line: f.line,
    selection: f.selection, confidences: f.confidences, team: f.team?.id, favourite: f.favourite,
    from: f.from, to: f.to ? `${f.to}T23:59:59.999Z` : null,
  };
  if (f.subject === 'recommendations') filters.thresholds = thresholdsFor(db, userId);
  const total = grouped(db, "'all'", filters)[0] ?? { n: 0 };
  let breakdown = null;
  if (f.groupBy === 'team') {
    breakdown = teamBreakdown(db, filters);
  } else if (f.groupBy && DIMENSION[f.groupBy]) {
    const names = f.groupBy === 'competition'
      ? new Map(db.prepare('SELECT id, name FROM competitions').all().map((r) => [r.id, r.name]))
      : f.groupBy === 'market' ? new Map(db.prepare('SELECT key, name FROM market_types').all().map((r) => [r.key, r.name])) : null;
    breakdown = grouped(db, DIMENSION[f.groupBy], filters)
      .map(({ reliability, ...r }) => ({ ...r, label: names?.get(r.key) ?? label(f.groupBy, r.key) }))
      .sort((a, b) => (f.groupBy === 'month' ? a.key.localeCompare(b.key) : b.n - a.n));
  }
  return { kind: 'predictions', total, breakdown, answer: predictionsSentence(f, total, breakdown) };
}

const label = (dim, key) => (dim === 'confidence' ? `${key[0].toUpperCase()}${key.slice(1)} confidence`
  : dim === 'source' ? (key === 'live' ? 'Live' : 'Backtest') : key);

function teamBreakdown(db, filters) {
  const name = db.prepare('SELECT name FROM teams WHERE id = ?');
  return grouped(db, 'team', filters)
    .filter((r) => r.n >= 30)
    .map(({ reliability, ...r }) => ({ ...r, label: name.get(r.key)?.name ?? String(r.key) }))
    .sort((a, b) => (b.logLoss ?? 0) - (a.logLoss ?? 0)).slice(0, 15);
}

function predictionsSentence(f, t, breakdown) {
  if (!t.n) return 'There are no graded selections that match this yet.';
  const what = f.restatement || 'These selections';
  const parts = [
    `${what}: ${Math.round(t.n).toLocaleString()} graded selection${t.n === 1 ? '' : 's'}.`,
    `The model said ${pct(t.saidPct)} on average and ${pct(t.hitPct)} came in`
      + ` — ${Math.abs(t.saidPct - t.hitPct) < 0.015 ? 'about right' : t.saidPct > t.hitPct ? 'it was too confident' : 'it was too cautious'}.`,
    `Brier score ${t.brier.toFixed(3)} against ${t.naiveBrier.toFixed(3)} for always guessing each selection's own hit rate`
      + (t.skill !== null ? ` (${t.skill >= 0 ? `${pct(t.skill)} better` : `${pct(-t.skill)} worse`}).` : '.'),
    `Average calibration error ${pct(t.ece)}.`,
  ];
  if (breakdown?.length > 1) {
    const ranked = [...breakdown].filter((b) => b.n >= 50 && b.ece !== null).sort((a, b) => a.ece - b.ece);
    if (ranked.length > 1) {
      parts.push(`Best calibrated: ${ranked[0].label} (${pct(ranked[0].ece)} error); least: ${ranked[ranked.length - 1].label} (${pct(ranked[ranked.length - 1].ece)}).`);
    }
  }
  return parts.join(' ');
}

function betsAnswer(db, userId, f) {
  const h = bettingHistory(db, userId, {
    from: f.from ? `${f.from}T00:00:00.000Z` : undefined, to: f.to ? `${f.to}T23:59:59.999Z` : undefined,
    competition: f.competitions[0] ? String(f.competitions[0].id) : undefined,
    market: f.markets[0], team: f.team?.name,
  });
  const t = h.totals;
  const money = (m) => formatMoney(m, h.currency);
  const by = { market: h.byMarket, competition: h.byCompetition, confidence: h.byConfidence, team: h.byTeam, month: h.byMonth }[f.groupBy] ?? null;
  let answer;
  if (!t.bets) answer = 'No recorded bets match this.';
  else {
    answer = `${f.restatement || 'Your bets'}: ${t.bets} bet${t.bets === 1 ? '' : 's'} (${t.settled} settled), `
      + `${t.won} won and ${t.lost} lost, profit ${money(t.profitMinor)} on ${money(t.stakedMinor)} bet`
      + `${t.roi !== null ? ` (ROI ${pct(t.roi)})` : ''}.`;
    if (t.closing.legs) {
      answer += ` Closing prices recorded for ${t.closing.legs} selection${t.closing.legs === 1 ? '' : 's'}: `
        + `you beat the close on ${t.closing.beat}, by ${pct(t.closing.averageClv)} on average.`;
    } else if (/clos/i.test(f.restatement)) {
      answer += ' No closing prices have been recorded yet — add them on My Bets to measure this.';
    }
  }
  return { kind: 'bets', currency: h.currency, total: t, breakdown: by, answer };
}

/** The whole question: parse with Claude, resolve, run. */
export async function ask(db, userId, question, parser) {
  const q = String(question ?? '').trim();
  if (q.length < 5) throw new ValidationError('Ask a question about SokkerLiga\'s predictions, recommendations or your bets.');
  if (q.length > 500) throw new ValidationError('Keep the question under 500 characters.');
  if (!parser) throw new ValidationError('Questions need Claude, and no Anthropic API key is configured on the server.', 503);
  const raw = await parser.parse(q, questionContext(db));
  if (!raw.understood) return { question: q, understood: false, clarification: raw.clarification };
  const filter = resolveFilter(db, raw);
  return { question: q, understood: true, filter: describe(filter), ...runFilter(db, userId, filter) };
}

/* The filter in words, shown back so it is clear what was measured. */
function describe(f) {
  const chips = [];
  chips.push({ predictions: 'Predictions', recommendations: 'Selections that pass your thresholds', bets: 'Your bets' }[f.subject]);
  if (f.subject !== 'bets') chips.push(f.source === 'live' ? 'Live only' : f.source === 'backtest' ? 'Backtest only' : 'Live and backtest');
  for (const c of f.competitions) chips.push(c.name);
  for (const m of f.markets) chips.push(m.replace(/_/g, ' '));
  if (f.line !== null) chips.push(`Line ${f.line}`);
  if (f.selection) chips.push(`Selection: ${f.selection.replace(/_/g, ' ')}`);
  for (const c of f.confidences) chips.push(`${c[0].toUpperCase()}${c.slice(1)} confidence`);
  if (f.team) chips.push(f.team.name);
  if (f.favourite) chips.push(`${f.favourite === 'home' ? 'Home' : 'Away'} favourites`);
  if (f.from || f.to) chips.push(`${f.from ?? 'Start'} to ${f.to ?? 'today'}`);
  if (f.groupBy) chips.push(`By ${f.groupBy}`);
  return { restatement: f.restatement, chips: chips.map((c) => c[0].toUpperCase() + c.slice(1)), notes: f.notes };
}
